call operator#user#define('convert-case-lower-camel', 'operator#convert_case#convert_to', 'let g:operator#convert_case#target_case = "lowerCamelCase"')
call operator#user#define('convert-case-upper-camel', 'operator#convert_case#convert_to', 'let g:operator#convert_case#target_case = "UpperCamelCase"')
call operator#user#define('convert-case-lower-snake', 'operator#convert_case#convert_to', 'let g:operator#convert_case#target_case = "lower_snake_case"')
call operator#user#define('convert-case-upper-snake', 'operator#convert_case#convert_to', 'let g:operator#convert_case#target_case = "UPPER_SNAKE_CASE"')
call operator#user#define('convert-case-toggle-upper-lower', 'operator#convert_case#toggle_upper_lower')
call operator#user#define('convert-case-loop', 'operator#convert_case#loop')
